#!/bin/sh -f
# this is a generic shell script wrapper for a cmsRun configuration file
#

if [ $# -lt 3 ]
then
    echo "Usage: submit.sh [nevents] [ptmin] [ptmax]"
    exit
fi

nevts=$1
ptmin=$2
ptmax=$3

echo
echo ">>> Beginning cmsRun execution on `date`  <<<"
echo ">>> Number of events to process: $nevts <<<"
echo ">>> pT hat bin: ${ptmin} - ${ptmax} <<<"
echo

# lsf provids a variable for the current working directory
# dir=$LS_SUBCWD
dir=$PWD
cd $dir
echo $dir

echo "Current directory $PWD"

#eval `scramv1 runtime -sh`
if [ -n "${CMS_PATH:-}" ]; then
  echo "CMSSW computing environment already setup"
else
  export SCRAM_ARCH=`scramv1 arch`
fi
eval `scramv1 runtime -sh`

export CFG=runit_${RANDOM}.cfg
cat > $CFG <<EOF
//
// top-level config file ready to run on cmsRun command line
//
process ANALYSIS  = {

    
    source = PoolSource {
	untracked vstring fileNames = {
	    "file:/uscmst1b_scratch/lpc1/cmsjtmet/apana/hlt/CSA07-152/HLTPoolOutput_QCD_pt${ptmin}-${ptmax}.root"
	}
    }
    untracked PSet maxEvents = {untracked int32 input = ${nevts}}
    include "FWCore/MessageLogger/data/MessageLogger.cfi"

    #include "Configuration/StandardSequences/data/FakeConditions.cff"
    #include "input/defaultInput.cfi"
    #include "input/mc-onsel-120_QCD_pt_50_80-OSFLoose-v2.cff"
    #include "input/mc-onsel-120_PU_Minbias-OSFDefault-v1.cff"
    #include "input/mc-onsel-120_QCD_pt_470_600.cff"

    es_module = CaloGeometryBuilder {}

   #Geometry
    include "Geometry/CMSCommonData/data/cmsSimIdealGeometryXML.cfi"

    module hltanalysisPE1 = HLTJetAnalyzer{
	# string recjets = "iterativeCone5CaloJets"
	string recjets = "MCJetCorJetIcone5"
	string genjets = "iterativeCone5GenJets"
	string recmet  = "met"
	string genmet  = "genMet"
	string hltobj  = "hlt1jet150"
	string calotowers = "towerMaker"
	InputTag l1collections= l1extraParticles
	PSet RunParameters =
	{
	    string HistogramFile = "analysis_pt${ptmin}_${ptmax}.root"
	    vstring HistParams = {"60","0","600"}
	    string HLTPath = "HLT1jetPE1"
	    bool Monte = true
	    bool Debug = false
	    double EtaMin   = -5.2
	    double EtaMax   = 5.2
	    bool WeightXS = true
	    string XSWeightFile = "xsweight.dat"
	}
    }
    
    path p1 = {hltanalysisPE1}
		
}		
EOF
echo -------------- Printing Configuation File ---------------------------
echo
cat $CFG
echo --------------- End of Configuation File ---------------------------
cmsRun -p $CFG
rm $CFG

echo
echo ">>> Ending cmsRun execution on `date`  <<<"
echo

exit
