#!/bin/csh
#
    echo " "
    echo "This script is: " ${0}
    echo -n "Starting date and time: "
    date
    echo " "
    echo "User:" $user
    echo -n "Current node:  "
    uname -a
    echo " "

    setenv EXEC bin/ReadDijetTree
    setenv HCOMMENT 10pb # add comment to output histogram. Comment out if unnecessary

    set outDir = hsts
    # set outDir = .
    set eta  = 3.0

    set nevt = -1 # number of events/file to process (use < 0 for all)
    # set nevts = (3926600 4131600 2506500 324850 88839 17121) # event for 1pb-1 total Lumi

    set doWeight = 1 # 1 (0) do (do not) weight events
    set jetAlgo = Scone7
    set engShift = -2 # 0 do not shift jet energies, +-1 flat 10%, +-2 linear shift

    set smrGenEng = 1 # 1 (0) smear (don't smear) genjet energies
    set do1pb = 0 # 1 (0) adjust (don't adjust) nevt and prescales for 1pb running
    set adjustMass = 0 

    set local = 0
    # foreach type (CaloMCCor Gen Calo)
    # foreach type (Gen)
    # foreach type (CaloMCCor)
    foreach type (Calo)
	foreach energy ( 20 30 50 80 110 150) 
	# foreach energy ( 30 150)
	# foreach energy ( 20 )
	    @ istream++
	    # set nevt = $nevts[$istream]
	    set eng = $energy
	    set stream = Jet"$energy"
	    #setenv INPUT /uscms_data/d1/cmsjtmet/kkousour/CSA08/Dijets/Dijet_JetET"$eng"_"$type"_Scone7.root
	    #setenv INPUT /uscmst1b_scratch/lpc1/cmsjtmet/apana/iCSA08/Dijet_JetET"$eng"_"$type"_Scone7.root

	    if ( $local == 1 ) then
		setenv INPUT /scratch/apana/iCSA08/Dijet_JetET"$eng"_"$type"_"$jetAlgo"_10pb.root
	    else
		setenv INPUT rfio:${CASTOR_HOME}/iCSA08/Dijet_JetET"$eng"_"$type"_"$jetAlgo"_10pb.root
	    endif

	    # create the input card file
	    setenv INPC userCards.dat.$$ 
	    echo $jetAlgo            >! $INPC
	    echo $outDir             >> $INPC
	    echo $stream             >> $INPC
	    echo $nevt               >> $INPC
	    echo $type               >> $INPC
	    echo $eta                >> $INPC
	    echo $doWeight           >> $INPC
	    echo $engShift           >> $INPC
	    echo $smrGenEng          >> $INPC
	    echo $do1pb              >> $INPC
	    echo $adjustMass         >> $INPC
	    echo "Input file $INPC"":"
	    cat $INPC

	    echo ""
	    #echo $INPUT
	    #echo $STREAM
	    
	    nice $EXEC $INPUT
	    \rm $INPC
	end # end loop over gen and calo
    end # end loop over energy

